spring.application.name=taskflow-backend
spring.datasource.url=jdbc:postgresql://localhost:5433/taskflow_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:postgres123}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=9e08e0ba9d6513
spring.mail.password=8eb3ea5f2561a4
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true